version: "3.1"

services:
  db:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=Thrash
    volumes:
      - ./thrash:/data/db
    ports:
      - 27017:27017
volumes:
  thrash:    